"""Collection metadata output files (.json, .bib, .md). See docs/architecture.md."""

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from lore_mcp.store import get_all_sources, list_sources, open_db


def generate_collection_json(db_path: str) -> str:
    """Generate a JSON metadata file alongside the .db file."""
    db = open_db(db_path)
    meta = dict(db.execute("SELECT key, value FROM meta").fetchall())
    sources = list_sources(db)
    biblio = get_all_sources(db)
    db.close()

    db_file = Path(db_path)
    sha256 = hashlib.sha256(db_file.read_bytes()).hexdigest()
    collection_name = db_file.stem

    data = {
        "collection": collection_name,
        "model_name": meta.get("model_name"),
        "model_dim": int(meta["model_dim"]) if "model_dim" in meta else None,
        "chunk_size": int(meta["chunk_size"]) if "chunk_size" in meta else None,
        "chunk_overlap": int(meta["chunk_overlap"]) if "chunk_overlap" in meta else None,
        "created_at": meta.get("created_at"),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "stats": {
            "file_count": len(sources),
            "chunk_count": sum(s["count"] for s in sources),
            "db_size_bytes": db_file.stat().st_size,
        },
        "sha256": sha256,
        "sources": [
            {k: v for k, v in s.items() if v is not None}
            for s in biblio
        ],
    }

    out_path = db_file.with_suffix(".json")
    out_path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    return str(out_path)


def generate_collection_bib(db_path: str) -> str:
    """Generate a BibTeX bibliography file alongside the .db file."""
    db = open_db(db_path)
    biblio = get_all_sources(db)
    db.close()

    entries = []
    for s in biblio:
        key = Path(s["source_file"]).stem.replace(" ", "_").replace("-", "_")
        fields = []
        if s.get("author"):
            fields.append(f"  author = {{{s['author']}}}")
        if s.get("title"):
            fields.append(f"  title = {{{s['title']}}}")
        if s.get("url"):
            fields.append(f"  url = {{{s['url']}}}")
        if s.get("date"):
            fields.append(f"  year = {{{s['date'][:4] if len(s['date']) >= 4 else s['date']}}}")
        if s.get("license"):
            fields.append(f"  note = {{License: {s['license']}}}")
        entries.append(f"@misc{{{key},\n" + ",\n".join(fields) + "\n}")

    out_path = Path(db_path).with_suffix(".bib")
    out_path.write_text("\n\n".join(entries) + "\n", encoding="utf-8")
    return str(out_path)


def generate_collection_md(db_path: str) -> str:
    """Generate a human-readable Markdown description alongside the .db file."""
    db = open_db(db_path)
    meta = dict(db.execute("SELECT key, value FROM meta").fetchall())
    sources = list_sources(db)
    biblio = get_all_sources(db)
    db.close()

    db_file = Path(db_path)
    name = db_file.stem
    total_chunks = sum(s["count"] for s in sources)

    lines = [
        f"# {name}",
        "",
        f"Collection generated by lore-mcp.",
        "",
        "## Parameters",
        "",
        f"- **Model:** {meta.get('model_name', 'unknown')}",
        f"- **Dimensions:** {meta.get('model_dim', 'unknown')}",
        f"- **Chunk size:** {meta.get('chunk_size', 'unknown')}",
        f"- **Chunk overlap:** {meta.get('chunk_overlap', 'unknown')}",
        f"- **Created:** {meta.get('created_at', 'unknown')}",
        "",
        "## Statistics",
        "",
        f"- **Files:** {len(sources)}",
        f"- **Chunks:** {total_chunks}",
        f"- **Database size:** {db_file.stat().st_size / 1024:.0f} KB",
        "",
        "## Sources",
        "",
    ]

    for s in biblio:
        title = s.get("title") or s["source_file"]
        author = f" — {s['author']}" if s.get("author") else ""
        license_info = f" ({s['license']})" if s.get("license") else ""
        url = f" [{s['url']}]({s['url']})" if s.get("url") else ""
        lines.append(f"- **{title}**{author}{license_info}{url}")

    if any(s.get("level") == "gris" for s in biblio):
        lines.extend([
            "",
            "## Notice",
            "",
            "Some sources in this collection have uncertain redistribution rights "
            "(level: gris). This collection is shared in good faith for personal use. "
            "No commercial exploitation. Removal on request from rights holders.",
        ])

    out_path = db_file.with_suffix(".md")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(out_path)


def generate_all(db_path: str) -> dict:
    """Generate all metadata files (.json, .bib, .md) for a collection."""
    return {
        "json": generate_collection_json(db_path),
        "bib": generate_collection_bib(db_path),
        "md": generate_collection_md(db_path),
    }
